### ISSUE TITLE
Traditional Chinese support?

### ISSUE THREAD

**Issue by large-passenger-carrying-vehicle** [xwgmdjc/GengShuang#3]
I can try to add Traditional Chinese support for this generator. It will make this generator easier to use for Hongkongers and others who cannot or do not want to read Simplified Chinese. I can make a fork, add support for it and PR it here. Should I do that?

**Comment by xwgmdjc** [comment]
多谢支持，您完成之后可以发 PR，我之后会将其合并的。

**Comment by laubonghaudoi** [comment]
應該直接加個OpenCC就得，唔會太複雜

**Comment by large-passenger-carrying-vehicle** [comment]
Lol, I just completed the PR without realising someone else has already done it
